:toc:
:toclevels: 5
:toc-placement!:
:source-highlighter: highlight.js
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= Qanary Explanation Service

:toc:

== Description

Question Answering components following the https://github.com/WDAqua/Qanary[Qanary methodology] mostly create outputs (e.g., https://github.com/WDAqua/Qanary-question-answering-components/tree/master/qanary-component-QB-BirthDataWikidata[a query builder component typically generates RDF data or SPARQL queries, respectively ]) and store them as new annotations to an RDF graph in the triplestore. 
To understand Qanary components it's helpful to have knowledge about the data they generate while acknowledging that this is only a first step in explaining the component or even QA systems.

This webservice provides some functionalities to compute explanations for some Qanary components in triplestore graphs.

== Build and Installation

=== Building

==== Building from scratch using Java

Create the .jar-file like so:

[source, bash]
----
mvn clean install
----

==== Building with Docker

Build an image with the existing Dockerfile like so

[source,bash]
----
docker build . -t <yourDesiredImageName>
----

=== Running the application

* while using the JAR file: 
+
--
** execute it like so `java -jar ./PATH/TO/PACKAGED_JAR.jar`
--
* while using the created Dockerfile:
+
--
** `docker run -p 12345:4000 <yourDesiredImageName>`
*** the "p"-tag is optional and maps the applications-port (4000) to another one, in this case and on a local machine the service would be available at "http://localhost:12345"
--

== Usage

* when accessing one of the following endpoints make sure to pass the required values as parameters
** when you're working with the curl command do it like so: `curl http://localhost:12345/explanation?graphID=<whateverGraphidYouHave>`
*** for more than one parameter: `curl "http://localhost:12345/explanation?graphID=<whateverGraphidYouHave>&<anotherParameter>=<ValueOfTheOtherParameter>"`, with attention to the ' " " '

=== Settings

Change the following as you need them:

.*applications.properties*
[source, ini]
----
server.port = 4000
sparqlEndpoint = http://demos.swe.htwk-leipzig.de:40111/sparql
----

=== Functionalities

Currently, there are several endpoints with different tasks, as of the latest version these are:

* `/explanation` 
+
--
*required parameter:*  graphURI (parsable as IRI)

*example request:* ...

*return:* a list of objects of all annotations which have the following structure  https://github.com/WDAqua/Qanary-question-answering-components/tree/master/qanary-component-NED-DBpediaSpotlight[qanary-component-NED-DBpediaSpotlight]

*SPARQL query:*
[source, sparql]
----
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX oa: <http://www.w3.org/ns/openannotation/core/>
PREFIX qa: <http://www.wdaqua.eu/qa#>
SELECT *
FROM ?graphURI

WHERE {
    ?annotationId a qa:AnnotationOfInstance.
    ?annotationId rdf:type ?type.
    ?annotationId oa:hasBody ?body.
    ?annotationId oa:hasTarget [
	a oa:SpecificResource;
                  oa:hasSource ?source;
                  oa:hasSelector [
    	a oa:TextPositionSelector;
                  oa:start ?start;
                  oa:end ?end;
    ]
].
    ?annotationId oa:annotatedBy $createdBy .
    ?annotationId oa:annotatedAt $createdAt .
    ?annotationId qa:score ?score .
}
----
--
* `/explanationforquerybuilder`
+
--
*required Parameter:*  graphURI (parsable as IRI)

*return:* a textual explanation with the created SPARQL-queries which has been created by every involved QB-component

*SPARQL query:*
[source,sparql]
----
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX oa: <http://www.w3.org/ns/openannotation/core/>
PREFIX qa: <http://www.wdaqua.eu/qa#>
SELECT *
FROM ?graphURI

WHERE {
    ?annotationId a qa:AnnotationOfAnswerSPARQL .
    ?annotationId oa:hasBody ?body .
    ?annotationId oa:annotatedBy $createdBy .
    ?annotationId oa:annotatedAt $createdAt .
    ?annotationId qa:score ?score .
}
----
--
* `/getannotations`
+
--
*required Parameter:*  graphURI (parsable as IRI)

*return:* a list of objects with all annotations (similar to `/explanation` but not as strict, see SPARQL-Query)

*SPARQL query:*
[source,sparql]
----
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX oa: <http://www.w3.org/ns/openannotation/core/>
PREFIX qa: <http://www.wdaqua.eu/qa#>
SELECT *
FROM ?graphURI
WHERE {
    ?annotationId rdf:type ?type.
    ?annotationId oa:hasBody ?body.
    ?annotationId oa:hasTarget ?target.
    ?annotationId oa:annotatedBy $createdBy .
    ?annotationId oa:annotatedAt $createdAt .
}
----
--
* `/explainspecificcomponent`
+
--
*required Parameter:*  graphURI (parsable as IRI), componentURI (parsable as IRI)

*return:* depending on the Accept-Header:

** *none*: Turtle
** *application/rdf+xml*: RDF/XML
** *application/ld+json*: JSONLD
** *other*: no response

*SPARQL query:*
[source,sparql]
----
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX oa: <http://www.w3.org/ns/openannotation/core/>
PREFIX qa: <http://www.wdaqua.eu/qa#>
SELECT *
FROM ?graphURI

WHERE {
    ?annotationId oa:annotatedBy ?componentURI .
    ?annotationId oa:hasBody ?body .
    ?annotationId oa:annotatedAt $createdAt .
    ?annotationId qa:score ?score .
}
----
--

=== Example 

. Firstly we start a QA process with the Question "What is the real name of Superman?" and the components
** NED-DBpediaSpotlight and
** QB-SimpleRealNameOfSuperhero
. As a result, we should get a `graphURI`
** in our example, let's assume it is `urn:graph:c55b5c85-6a89-4dd6-83bc-3b6d1ea953ea`
. Now, we can use this graphURI or a different one (maybe one where we don't know the acting components) for some requests against the webservice 
** to get all annotations we could execute the following curl in a terminal
*** `curl http://localhost:12345/getannotations?graphID=urn:graph:c55b5c85-6a89-4dd6-83bc-3b6d1ea953ea`
** As a result, we should get an array of objects containing the properties from the SPARQL query

.Ergebnis
[%collapsible]
====
[source,json]
----
[
    {
        "source": null,
        "start": null,
        "end": null,
        "body": {
            "type": "uri",
            "value": "http://dbpedia.org/resource/String_theory"
        },
        "type": {
            "type": "uri",
            "value": "http://www.wdaqua.eu/qa#AnnotationOfInstance"
        },
        "createdBy": {
            "type": "uri",
            "value": "urn:qanary:NED-DBpediaSpotlight"
        },
        "createdAt": {
            "value": "2023-08-22T12:17:24.848",
            "type": "typed-literal",
            "datatype": "http://www.w3.org/2001/XMLSchema#dateTime"
        },
        "score": {
            "value": 0.9347568085631697,
            "type": "typed-literal",
            "datatype": "http://www.w3.org/2001/XMLSchema#decimal"
        },
        "entity": null,
        "target": {
            "type": "bnode",
            "value": "b0"
        },
        "annotationID": {
            "type": "uri",
            "value": "tag:stardog:api:0.42490125431422954"
        },
        "annotationId": {
            "type": "uri",
            "value": "tag:stardog:api:0.42490125431422954"
        }
    },
    {
        "source": null,
        "start": null,
        "end": null,
        "body": {
            "type": "uri",
            "value": "http://dbpedia.org/resource/Real_number"
        },
        "type": {
            "type": "uri",
            "value": "http://www.wdaqua.eu/qa#AnnotationOfInstance"
        },
        "createdBy": {
            "type": "uri",
            "value": "urn:qanary:NED-DBpediaSpotlight"
        },
        "createdAt": {
            "value": "2023-08-22T12:17:25.052",
            "type": "typed-literal",
            "datatype": "http://www.w3.org/2001/XMLSchema#dateTime"
        },
        "score": {
            "value": 0.977747974809564,
            "type": "typed-literal",
            "datatype": "http://www.w3.org/2001/XMLSchema#decimal"
        },
        "entity": null,
        "target": {
            "type": "bnode",
            "value": "b1"
        },
        "annotationID": {
            "type": "uri",
            "value": "tag:stardog:api:0.39515999164525084"
        },
        "annotationId": {
            "type": "uri",
            "value": "tag:stardog:api:0.39515999164525084"
        }
    },
    {
        "source": null,
        "start": null,
        "end": null,
        "body": {
            "type": "uri",
            "value": "http://dbpedia.org/resource/Superman"
        },
        "type": {
            "type": "uri",
            "value": "http://www.wdaqua.eu/qa#AnnotationOfInstance"
        },
        "createdBy": {
            "type": "uri",
            "value": "urn:qanary:NED-DBpediaSpotlight"
        },
        "createdAt": {
            "value": "2023-08-22T12:17:25.265",
            "type": "typed-literal",
            "datatype": "http://www.w3.org/2001/XMLSchema#dateTime"
        },
        "score": {
            "value": 0.999238163684283,
            "type": "typed-literal",
            "datatype": "http://www.w3.org/2001/XMLSchema#decimal"
        },
        "entity": null,
        "target": {
            "type": "bnode",
            "value": "b2"
        },
        "annotationID": {
            "type": "uri",
            "value": "tag:stardog:api:0.23587012456677092"
        },
        "annotationId": {
            "type": "uri",
            "value": "tag:stardog:api:0.23587012456677092"
        }
    },
    {
        "source": null,
        "start": null,
        "end": null,
        "body": {
            "type": "literal",
            "value": "PREFIX  rdfs: <http://www.w3.org/2000/01/rdf-schema#>\nPREFIX  dct:  <http://purl.org/dc/terms/>\nPREFIX  dbr:  <http://dbpedia.org/resource/>\nPREFIX  rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>\nPREFIX  foaf: <http://xmlns.com/foaf/0.1/>\n\nSELECT  *\nWHERE\n  { ?resource  foaf:name  ?answer ;\n              rdfs:label  ?label\n    FILTER ( lang(?label) = \"en\" )\n    ?resource  dct:subject  dbr:Category:Superheroes_with_alter_egos\n    FILTER ( ! strstarts(lcase(?label), lcase(?answer)) )\n    VALUES ?resource { dbr:Superman }\n  }\nORDER BY ?resource\n"
        },
        "type": {
            "type": "uri",
            "value": "http://www.wdaqua.eu/qa#AnnotationOfAnswerSPARQL"
        },
        "createdBy": {
            "type": "uri",
            "value": "urn:qanary:QB-SimpleRealNameOfSuperHero"
        },
        "createdAt": {
            "value": "2023-08-22T12:17:26.104",
            "type": "typed-literal",
            "datatype": "http://www.w3.org/2001/XMLSchema#dateTime"
        },
        "score": {
            "value": 1.0,
            "type": "typed-literal",
            "datatype": "http://www.w3.org/2001/XMLSchema#float"
        },
        "entity": null,
        "target": {
            "type": "uri",
            "value": "http://demos.swe.htwk-leipzig.de:40111/question/stored-question__text_57bede26-f976-4946-97c2-993acddfdd08"
        },
        "annotationID": {
            "type": "uri",
            "value": "tag:stardog:api:0.4428726379989152"
        },
        "annotationId": {
            "type": "uri",
            "value": "tag:stardog:api:0.4428726379989152"
        }
    }
]
----
====
