PREFIX  qa:   <http://www.wdaqua.eu/qa#>
PREFIX  oa:   <http://www.w3.org/ns/openannotation/core/>
PREFIX  rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  x:    <http://example.org#>
PREFIX  prov: <http://www.w3.org/ns/prov#>

SELECT  ?id ?caller ?callerName ?method ?annotatedBy ?outputDataType ?outputDataValue ?annotatedAt (GROUP_CONCAT(?inputDataValue; SEPARATOR=",") AS ?inputDataValues) (GROUP_CONCAT(?inputDataType; SEPARATOR=",") AS ?inputDataTypes)
FROM <urn:graph:c8b0552f-be96-40c5-aa27-47191d2707cd>
WHERE {
  BIND(?methodIdentifier AS ?id)
  BIND(?component AS ?annotatedBy)
  ?id  rdf:type              qa:AnnotationOfLogMethod ;
        prov:actedOnBehalfOf  ?caller .
  		?caller qa:methodName ?callerName .
        ?id qa:methodName         ?method ;
        oa:annotatedAt        ?annotatedAt ;
        oa:annotatedBy        ?annotatedBy .

        OPTIONAL {
        ?id x:output [ rdf:type ?outputDataType ; rdf:value ?outputDataValue ] ;
  		}
  		OPTIONAL {
	    ?id x:input ?input .
  		?input (rdf:rest*/rdf:first) ?item .
  		?item rdf:type ?inputDataType ;
        	  rdf:value ?inputDataValue .
  		}
}
GROUP BY ?id ?caller ?callerName ?outputDataType ?outputDataValue ?annotatedAt ?annotatedBy ?method
