PREFIX  qa:   <http://www.wdaqua.eu/qa#>
PREFIX  oa:   <http://www.w3.org/ns/openannotation/core/>
PREFIX  rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  x:    <http://example.org#>
PREFIX  prov: <http://www.w3.org/ns/prov#>

SELECT  ?id ?caller ?method ?outputDataType ?outputDataValue ?annotatedAt ?annotatedBy (GROUP_CONCAT(?inputDataValue;SEPARATOR=",") AS ?inputDataValues) (GROUP_CONCAT(?inputDataType;SEPARATOR=",") AS ?inputDataTypes)
FROM ?graph
WHERE {
  ?id  rdf:type              qa:AnnotationOfLogMethod ;
        prov:actedOnBehalfOf  ?caller ;
        qa:methodName         ?method ;
        x:output [ rdf:type ?outputDataType ; rdf:value ?outputDataValue ] ;
        x:input ?input .
            ?input (rdf:rest*/rdf:first) ?item .
            ?item rdf:type ?inputDataType ;
                  rdf:value ?inputDataValue .
   ?id  oa:annotatedAt        ?annotatedAt ;
        oa:annotatedBy        ?annotatedBy .
} GROUP BY ?id ?caller ?method ?outputDataType ?outputDataValue ?annotatedAt ?annotatedBy



