PREFIX aex: <http://www.semanticweb.org/dennisschiese/ontologies/2023/9/automatedExplanation>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>


INSERT {
    GRAPH ?graph{                                       // probably specify graph
        ?annotationID   aex:prompt  ?prompt;
                        aex:gptExplanation ?gptExplanation;
                        aex:testData [
                            aex:usedComponent ?usedComponent;
                            aex:usedComponentAsNum ?usedComponentAsNum;
                            aex:dataset ?dataset;
                            aex:graphID ?graphID;
                            aex:explanation ?explanation;
                            aex:questionID ?questionID;
                            aex:question ?question
                        ];
                        aex:exampleData rdf:Seq;
                            ?exampleDataSequence .
    }
}