PREFIX aex: <http://www.semanticweb.org/dennisschiese/ontologies/2023/9/automatedExplanation>

INSERT {

    GRAPH <urn:bulkload:general> {

        ?experimentId   aex:prompt  ?prompt ;
                        aex:gptExplanation  ?gptExplanation ;
                        aex:usedComponent   ?usedComponent ;
                        aex:usedComponentAsNum  ?usedComponentAsNum ;
                        aex:dataset ?dataset ;
                        aex:graphId ?graphId ;
                        aex:explanation ?explanation ;
                        aex:questionId  ?questionId ;
                        aex:question    ?question ;
                        aex:exampleData rdf:Seq ;
                        ?exampleDataSeq .
    }

}