PREFIX oa: <http://www.w3.org/ns/openannotation/core/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

SELECT DISTINCT ?component ?questionId
FROM ?graph
WHERE {
    ?s oa:annotatedBy ?component .
	?questionId owl:sameAs <urn:qanary:currentQuestion> .
}