name: Docker Image CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag component-explanation:latest
      - name: Docker Login
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Tag latest docker image
        if: startsWith(github.ref, 'refs/tags/')
        run: docker tag component-explanation:latest wseresearch/component-explanation:latest
      - name: Tag docker image version
        if: startsWith(github.ref, 'refs/tags/')
        run: docker tag component-explanation:latest "wseresearch/component-explanation:${{ github.ref_name }}"
      - name: Push latest docker image
        if: startsWith(github.ref, 'refs/tags/')
        run: docker push wseresearch/component-explanation:latest
      - name: Push docker image version
        if: startsWith(github.ref, 'refs/tags/')
        run: docker push "wseresearch/component-explanation:${{ github.ref_name }}"
      - name: Init update
        if: startsWith(github.ref, 'refs/tags/')
        uses: WSE-research/docker-service-updater@v0.2.1
        with:
          updater_host: ${{ secrets.UPDATER_HOST }}
          api_key: ${{ secrets.API_KEY }}
